// Code generated by MockGen. DO NOT EDIT.
// Source: ../../service/membership_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/giakiet05/lkforum/internal/dto"
	model "github.com/giakiet05/lkforum/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockMembershipService is a mock of MembershipService interface.
type MockMembershipService struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipServiceMockRecorder
}

// MockMembershipServiceMockRecorder is the mock recorder for MockMembershipService.
type MockMembershipServiceMockRecorder struct {
	mock *MockMembershipService
}

// NewMockMembershipService creates a new mock instance.
func NewMockMembershipService(ctrl *gomock.Controller) *MockMembershipService {
	mock := &MockMembershipService{ctrl: ctrl}
	mock.recorder = &MockMembershipServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembershipService) EXPECT() *MockMembershipServiceMockRecorder {
	return m.recorder
}

// CreateMembership mocks base method.
func (m *MockMembershipService) CreateMembership(req *dto.CreateMembershipRequest, userID string) (*model.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMembership", req, userID)
	ret0, _ := ret[0].(*model.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMembership indicates an expected call of CreateMembership.
func (mr *MockMembershipServiceMockRecorder) CreateMembership(req, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMembership", reflect.TypeOf((*MockMembershipService)(nil).CreateMembership), req, userID)
}

// DeleteMembership mocks base method.
func (m *MockMembershipService) DeleteMembership(req *dto.DeleteMembershipRequest, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMembership", req, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMembership indicates an expected call of DeleteMembership.
func (mr *MockMembershipServiceMockRecorder) DeleteMembership(req, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMembership", reflect.TypeOf((*MockMembershipService)(nil).DeleteMembership), req, userID)
}

// GetAllMemberships mocks base method.
func (m *MockMembershipService) GetAllMemberships(page, pageSize int) (*dto.PaginatedMembershipsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMemberships", page, pageSize)
	ret0, _ := ret[0].(*dto.PaginatedMembershipsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMemberships indicates an expected call of GetAllMemberships.
func (mr *MockMembershipServiceMockRecorder) GetAllMemberships(page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMemberships", reflect.TypeOf((*MockMembershipService)(nil).GetAllMemberships), page, pageSize)
}

// GetMembersCount mocks base method.
func (m *MockMembershipService) GetMembersCount(communityID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembersCount", communityID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembersCount indicates an expected call of GetMembersCount.
func (mr *MockMembershipServiceMockRecorder) GetMembersCount(communityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembersCount", reflect.TypeOf((*MockMembershipService)(nil).GetMembersCount), communityID)
}

// GetMembershipByCommunityID mocks base method.
func (m *MockMembershipService) GetMembershipByCommunityID(communityID string, page, pageSize int) (*dto.PaginatedMembershipsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembershipByCommunityID", communityID, page, pageSize)
	ret0, _ := ret[0].(*dto.PaginatedMembershipsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembershipByCommunityID indicates an expected call of GetMembershipByCommunityID.
func (mr *MockMembershipServiceMockRecorder) GetMembershipByCommunityID(communityID, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembershipByCommunityID", reflect.TypeOf((*MockMembershipService)(nil).GetMembershipByCommunityID), communityID, page, pageSize)
}

// GetMembershipByID mocks base method.
func (m *MockMembershipService) GetMembershipByID(membershipID string) (*model.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembershipByID", membershipID)
	ret0, _ := ret[0].(*model.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembershipByID indicates an expected call of GetMembershipByID.
func (mr *MockMembershipServiceMockRecorder) GetMembershipByID(membershipID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembershipByID", reflect.TypeOf((*MockMembershipService)(nil).GetMembershipByID), membershipID)
}

// GetMembershipsByUserID mocks base method.
func (m *MockMembershipService) GetMembershipsByUserID(userID string) ([]*model.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembershipsByUserID", userID)
	ret0, _ := ret[0].([]*model.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembershipsByUserID indicates an expected call of GetMembershipsByUserID.
func (mr *MockMembershipServiceMockRecorder) GetMembershipsByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembershipsByUserID", reflect.TypeOf((*MockMembershipService)(nil).GetMembershipsByUserID), userID)
}

// StartRedisToMongoMembershipSync mocks base method.
func (m *MockMembershipService) StartRedisToMongoMembershipSync() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartRedisToMongoMembershipSync")
}

// StartRedisToMongoMembershipSync indicates an expected call of StartRedisToMongoMembershipSync.
func (mr *MockMembershipServiceMockRecorder) StartRedisToMongoMembershipSync() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartRedisToMongoMembershipSync", reflect.TypeOf((*MockMembershipService)(nil).StartRedisToMongoMembershipSync))
}

// decreaseMembersCount mocks base method.
func (m *MockMembershipService) decreaseMembersCount(communityID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "decreaseMembersCount", communityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// decreaseMembersCount indicates an expected call of decreaseMembersCount.
func (mr *MockMembershipServiceMockRecorder) decreaseMembersCount(communityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "decreaseMembersCount", reflect.TypeOf((*MockMembershipService)(nil).decreaseMembersCount), communityID)
}

// ensureMembersCountExists mocks base method.
func (m *MockMembershipService) ensureMembersCountExists(communityID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ensureMembersCountExists", communityID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ensureMembersCountExists indicates an expected call of ensureMembersCountExists.
func (mr *MockMembershipServiceMockRecorder) ensureMembersCountExists(communityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ensureMembersCountExists", reflect.TypeOf((*MockMembershipService)(nil).ensureMembersCountExists), communityID)
}

// increaseMembersCount mocks base method.
func (m *MockMembershipService) increaseMembersCount(communityID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "increaseMembersCount", communityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// increaseMembersCount indicates an expected call of increaseMembersCount.
func (mr *MockMembershipServiceMockRecorder) increaseMembersCount(communityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "increaseMembersCount", reflect.TypeOf((*MockMembershipService)(nil).increaseMembersCount), communityID)
}

// syncMemberCounts mocks base method.
func (m *MockMembershipService) syncMemberCounts() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "syncMemberCounts")
	ret0, _ := ret[0].(error)
	return ret0
}

// syncMemberCounts indicates an expected call of syncMemberCounts.
func (mr *MockMembershipServiceMockRecorder) syncMemberCounts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "syncMemberCounts", reflect.TypeOf((*MockMembershipService)(nil).syncMemberCounts))
}
