// Code generated by MockGen. DO NOT EDIT.
// Source: ../../service/community_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	dto "github.com/giakiet05/lkforum/internal/dto"
	model "github.com/giakiet05/lkforum/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockCommunityService is a mock of CommunityService interface.
type MockCommunityService struct {
	ctrl     *gomock.Controller
	recorder *MockCommunityServiceMockRecorder
}

// MockCommunityServiceMockRecorder is the mock recorder for MockCommunityService.
type MockCommunityServiceMockRecorder struct {
	mock *MockCommunityService
}

// NewMockCommunityService creates a new mock instance.
func NewMockCommunityService(ctrl *gomock.Controller) *MockCommunityService {
	mock := &MockCommunityService{ctrl: ctrl}
	mock.recorder = &MockCommunityServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommunityService) EXPECT() *MockCommunityServiceMockRecorder {
	return m.recorder
}

// AddModerator mocks base method.
func (m *MockCommunityService) AddModerator(req *dto.AddModeratorRequest, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddModerator", req, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddModerator indicates an expected call of AddModerator.
func (mr *MockCommunityServiceMockRecorder) AddModerator(req, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddModerator", reflect.TypeOf((*MockCommunityService)(nil).AddModerator), req, userID)
}

// CreateCommunity mocks base method.
func (m *MockCommunityService) CreateCommunity(req *dto.CreateCommunityRequest, userID string) (*model.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCommunity", req, userID)
	ret0, _ := ret[0].(*model.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCommunity indicates an expected call of CreateCommunity.
func (mr *MockCommunityServiceMockRecorder) CreateCommunity(req, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCommunity", reflect.TypeOf((*MockCommunityService)(nil).CreateCommunity), req, userID)
}

// DeleteCommunityByID mocks base method.
func (m *MockCommunityService) DeleteCommunityByID(communityID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCommunityByID", communityID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCommunityByID indicates an expected call of DeleteCommunityByID.
func (mr *MockCommunityServiceMockRecorder) DeleteCommunityByID(communityID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCommunityByID", reflect.TypeOf((*MockCommunityService)(nil).DeleteCommunityByID), communityID, userID)
}

// GetAllCommunitiesPaginated mocks base method.
func (m *MockCommunityService) GetAllCommunitiesPaginated(page, pageSize int) (*dto.PaginatedCommunitiesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCommunitiesPaginated", page, pageSize)
	ret0, _ := ret[0].(*dto.PaginatedCommunitiesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCommunitiesPaginated indicates an expected call of GetAllCommunitiesPaginated.
func (mr *MockCommunityServiceMockRecorder) GetAllCommunitiesPaginated(page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCommunitiesPaginated", reflect.TypeOf((*MockCommunityService)(nil).GetAllCommunitiesPaginated), page, pageSize)
}

// GetCommunitiesByModeratorIDPaginated mocks base method.
func (m *MockCommunityService) GetCommunitiesByModeratorIDPaginated(moderatorID string, page, pageSize int) (*dto.PaginatedCommunitiesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommunitiesByModeratorIDPaginated", moderatorID, page, pageSize)
	ret0, _ := ret[0].(*dto.PaginatedCommunitiesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommunitiesByModeratorIDPaginated indicates an expected call of GetCommunitiesByModeratorIDPaginated.
func (mr *MockCommunityServiceMockRecorder) GetCommunitiesByModeratorIDPaginated(moderatorID, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommunitiesByModeratorIDPaginated", reflect.TypeOf((*MockCommunityService)(nil).GetCommunitiesByModeratorIDPaginated), moderatorID, page, pageSize)
}

// GetCommunitiesFilter mocks base method.
func (m *MockCommunityService) GetCommunitiesFilter(name, description string, is18Plus bool, createFrom time.Time, page, pageSize int) (*dto.PaginatedCommunitiesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommunitiesFilter", name, description, is18Plus, createFrom, page, pageSize)
	ret0, _ := ret[0].(*dto.PaginatedCommunitiesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommunitiesFilter indicates an expected call of GetCommunitiesFilter.
func (mr *MockCommunityServiceMockRecorder) GetCommunitiesFilter(name, description, is18Plus, createFrom, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommunitiesFilter", reflect.TypeOf((*MockCommunityService)(nil).GetCommunitiesFilter), name, description, is18Plus, createFrom, page, pageSize)
}

// GetCommunityByID mocks base method.
func (m *MockCommunityService) GetCommunityByID(id string) (*model.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommunityByID", id)
	ret0, _ := ret[0].(*model.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommunityByID indicates an expected call of GetCommunityByID.
func (mr *MockCommunityServiceMockRecorder) GetCommunityByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommunityByID", reflect.TypeOf((*MockCommunityService)(nil).GetCommunityByID), id)
}

// IsModerator mocks base method.
func (m *MockCommunityService) IsModerator(community *model.Community, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsModerator", community, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsModerator indicates an expected call of IsModerator.
func (mr *MockCommunityServiceMockRecorder) IsModerator(community, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsModerator", reflect.TypeOf((*MockCommunityService)(nil).IsModerator), community, userID)
}

// RemoveModerator mocks base method.
func (m *MockCommunityService) RemoveModerator(req *dto.RemoveModeratorRequest, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveModerator", req, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveModerator indicates an expected call of RemoveModerator.
func (mr *MockCommunityServiceMockRecorder) RemoveModerator(req, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveModerator", reflect.TypeOf((*MockCommunityService)(nil).RemoveModerator), req, userID)
}

// Start mocks base method.
func (m *MockCommunityService) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockCommunityServiceMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockCommunityService)(nil).Start))
}

// UpdateCommunity mocks base method.
func (m *MockCommunityService) UpdateCommunity(req *dto.UpdateCommunityRequest, userID string) (*model.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCommunity", req, userID)
	ret0, _ := ret[0].(*model.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCommunity indicates an expected call of UpdateCommunity.
func (mr *MockCommunityServiceMockRecorder) UpdateCommunity(req, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCommunity", reflect.TypeOf((*MockCommunityService)(nil).UpdateCommunity), req, userID)
}
