// Code generated by MockGen. DO NOT EDIT.
// Source: ../../service/auth_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/giakiet05/lkforum/internal/model"
	service "github.com/giakiet05/lkforum/internal/service"
	gomock "github.com/golang/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// CompleteGoogleSetup mocks base method.
func (m *MockAuthService) CompleteGoogleSetup(setupToken, username string) (*model.User, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteGoogleSetup", setupToken, username)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// CompleteGoogleSetup indicates an expected call of CompleteGoogleSetup.
func (mr *MockAuthServiceMockRecorder) CompleteGoogleSetup(setupToken, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteGoogleSetup", reflect.TypeOf((*MockAuthService)(nil).CompleteGoogleSetup), setupToken, username)
}

// CompleteRegistration mocks base method.
func (m *MockAuthService) CompleteRegistration(verificationToken, username, password string) (*model.User, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteRegistration", verificationToken, username, password)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// CompleteRegistration indicates an expected call of CompleteRegistration.
func (mr *MockAuthServiceMockRecorder) CompleteRegistration(verificationToken, username, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteRegistration", reflect.TypeOf((*MockAuthService)(nil).CompleteRegistration), verificationToken, username, password)
}

// Login mocks base method.
func (m *MockAuthService) Login(identifier, password string) (*model.User, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", identifier, password)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceMockRecorder) Login(identifier, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthService)(nil).Login), identifier, password)
}

// Logout mocks base method.
func (m *MockAuthService) Logout(accessToken, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", accessToken, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceMockRecorder) Logout(accessToken, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthService)(nil).Logout), accessToken, refreshToken)
}

// ProcessGoogleCallback mocks base method.
func (m *MockAuthService) ProcessGoogleCallback(code string) (*service.GoogleAuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessGoogleCallback", code)
	ret0, _ := ret[0].(*service.GoogleAuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessGoogleCallback indicates an expected call of ProcessGoogleCallback.
func (mr *MockAuthServiceMockRecorder) ProcessGoogleCallback(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessGoogleCallback", reflect.TypeOf((*MockAuthService)(nil).ProcessGoogleCallback), code)
}

// RefreshToken mocks base method.
func (m *MockAuthService) RefreshToken(refreshToken string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", refreshToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockAuthServiceMockRecorder) RefreshToken(refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockAuthService)(nil).RefreshToken), refreshToken)
}

// ResendOTP mocks base method.
func (m *MockAuthService) ResendOTP(email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResendOTP", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResendOTP indicates an expected call of ResendOTP.
func (mr *MockAuthServiceMockRecorder) ResendOTP(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResendOTP", reflect.TypeOf((*MockAuthService)(nil).ResendOTP), email)
}

// SendEmailVerification mocks base method.
func (m *MockAuthService) SendEmailVerification(email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmailVerification", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmailVerification indicates an expected call of SendEmailVerification.
func (mr *MockAuthServiceMockRecorder) SendEmailVerification(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmailVerification", reflect.TypeOf((*MockAuthService)(nil).SendEmailVerification), email)
}

// VerifyEmailCode mocks base method.
func (m *MockAuthService) VerifyEmailCode(email, otp string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmailCode", email, otp)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyEmailCode indicates an expected call of VerifyEmailCode.
func (mr *MockAuthServiceMockRecorder) VerifyEmailCode(email, otp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmailCode", reflect.TypeOf((*MockAuthService)(nil).VerifyEmailCode), email, otp)
}
