// Code generated by MockGen. DO NOT EDIT.
// Source: ../../service/post_history_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/giakiet05/lkforum/internal/dto"
	model "github.com/giakiet05/lkforum/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockPostHistoryService is a mock of PostHistoryService interface.
type MockPostHistoryService struct {
	ctrl     *gomock.Controller
	recorder *MockPostHistoryServiceMockRecorder
}

// MockPostHistoryServiceMockRecorder is the mock recorder for MockPostHistoryService.
type MockPostHistoryServiceMockRecorder struct {
	mock *MockPostHistoryService
}

// NewMockPostHistoryService creates a new mock instance.
func NewMockPostHistoryService(ctrl *gomock.Controller) *MockPostHistoryService {
	mock := &MockPostHistoryService{ctrl: ctrl}
	mock.recorder = &MockPostHistoryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostHistoryService) EXPECT() *MockPostHistoryServiceMockRecorder {
	return m.recorder
}

// CreatePostHistories mocks base method.
func (m *MockPostHistoryService) CreatePostHistories(requests []*dto.CreatePostHistoryRequest, requesterID string) ([]*model.PostHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePostHistories", requests, requesterID)
	ret0, _ := ret[0].([]*model.PostHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePostHistories indicates an expected call of CreatePostHistories.
func (mr *MockPostHistoryServiceMockRecorder) CreatePostHistories(requests, requesterID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePostHistories", reflect.TypeOf((*MockPostHistoryService)(nil).CreatePostHistories), requests, requesterID)
}

// CreatePostHistory mocks base method.
func (m *MockPostHistoryService) CreatePostHistory(request *dto.CreatePostHistoryRequest, requesterID string) (*model.PostHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePostHistory", request, requesterID)
	ret0, _ := ret[0].(*model.PostHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePostHistory indicates an expected call of CreatePostHistory.
func (mr *MockPostHistoryServiceMockRecorder) CreatePostHistory(request, requesterID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePostHistory", reflect.TypeOf((*MockPostHistoryService)(nil).CreatePostHistory), request, requesterID)
}

// DeletePostHistoryByID mocks base method.
func (m *MockPostHistoryService) DeletePostHistoryByID(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePostHistoryByID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePostHistoryByID indicates an expected call of DeletePostHistoryByID.
func (mr *MockPostHistoryServiceMockRecorder) DeletePostHistoryByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePostHistoryByID", reflect.TypeOf((*MockPostHistoryService)(nil).DeletePostHistoryByID), id)
}

// GetPostHistoryByID mocks base method.
func (m *MockPostHistoryService) GetPostHistoryByID(id, requesterID string) (*model.PostHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostHistoryByID", id, requesterID)
	ret0, _ := ret[0].(*model.PostHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostHistoryByID indicates an expected call of GetPostHistoryByID.
func (mr *MockPostHistoryServiceMockRecorder) GetPostHistoryByID(id, requesterID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostHistoryByID", reflect.TypeOf((*MockPostHistoryService)(nil).GetPostHistoryByID), id, requesterID)
}

// GetPostHistoryByUserID mocks base method.
func (m *MockPostHistoryService) GetPostHistoryByUserID(userID, requesterID string, page, pageSize int) (*dto.PaginatedPostHistoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostHistoryByUserID", userID, requesterID, page, pageSize)
	ret0, _ := ret[0].(*dto.PaginatedPostHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostHistoryByUserID indicates an expected call of GetPostHistoryByUserID.
func (mr *MockPostHistoryServiceMockRecorder) GetPostHistoryByUserID(userID, requesterID, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostHistoryByUserID", reflect.TypeOf((*MockPostHistoryService)(nil).GetPostHistoryByUserID), userID, requesterID, page, pageSize)
}
