// Code generated by MockGen. DO NOT EDIT.
// Source: ../../service/post_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	multipart "mime/multipart"
	reflect "reflect"

	dto "github.com/giakiet05/lkforum/internal/dto"
	model "github.com/giakiet05/lkforum/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockPostService is a mock of PostService interface.
type MockPostService struct {
	ctrl     *gomock.Controller
	recorder *MockPostServiceMockRecorder
}

// MockPostServiceMockRecorder is the mock recorder for MockPostService.
type MockPostServiceMockRecorder struct {
	mock *MockPostService
}

// NewMockPostService creates a new mock instance.
func NewMockPostService(ctrl *gomock.Controller) *MockPostService {
	mock := &MockPostService{ctrl: ctrl}
	mock.recorder = &MockPostServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostService) EXPECT() *MockPostServiceMockRecorder {
	return m.recorder
}

// AddImagesToPost mocks base method.
func (m *MockPostService) AddImagesToPost(userID, postID string, form *multipart.Form) ([]*model.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddImagesToPost", userID, postID, form)
	ret0, _ := ret[0].([]*model.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddImagesToPost indicates an expected call of AddImagesToPost.
func (mr *MockPostServiceMockRecorder) AddImagesToPost(userID, postID, form interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddImagesToPost", reflect.TypeOf((*MockPostService)(nil).AddImagesToPost), userID, postID, form)
}

// AddPollOptions mocks base method.
func (m *MockPostService) AddPollOptions(userID, postID string, options []string) (*dto.PollResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPollOptions", userID, postID, options)
	ret0, _ := ret[0].(*dto.PollResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPollOptions indicates an expected call of AddPollOptions.
func (mr *MockPostServiceMockRecorder) AddPollOptions(userID, postID, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPollOptions", reflect.TypeOf((*MockPostService)(nil).AddPollOptions), userID, postID, options)
}

// CreatePost mocks base method.
func (m *MockPostService) CreatePost(userID string, req *dto.CreatePostRequest) (*dto.PostResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", userID, req)
	ret0, _ := ret[0].(*dto.PostResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockPostServiceMockRecorder) CreatePost(userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockPostService)(nil).CreatePost), userID, req)
}

// DeletePost mocks base method.
func (m *MockPostService) DeletePost(postID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePost", postID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePost indicates an expected call of DeletePost.
func (mr *MockPostServiceMockRecorder) DeletePost(postID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePost", reflect.TypeOf((*MockPostService)(nil).DeletePost), postID, userID)
}

// GetPostByID mocks base method.
func (m *MockPostService) GetPostByID(postID, userID string) (*dto.PostResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostByID", postID, userID)
	ret0, _ := ret[0].(*dto.PostResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostByID indicates an expected call of GetPostByID.
func (mr *MockPostServiceMockRecorder) GetPostByID(postID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostByID", reflect.TypeOf((*MockPostService)(nil).GetPostByID), postID, userID)
}

// GetPosts mocks base method.
func (m *MockPostService) GetPosts(userID string, query *dto.GetPostsQuery) (*dto.PaginatedPostsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPosts", userID, query)
	ret0, _ := ret[0].(*dto.PaginatedPostsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPosts indicates an expected call of GetPosts.
func (mr *MockPostServiceMockRecorder) GetPosts(userID, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPosts", reflect.TypeOf((*MockPostService)(nil).GetPosts), userID, query)
}

// RemoveImagesFromPost mocks base method.
func (m *MockPostService) RemoveImagesFromPost(userID, postID string, publicIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveImagesFromPost", userID, postID, publicIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveImagesFromPost indicates an expected call of RemoveImagesFromPost.
func (mr *MockPostServiceMockRecorder) RemoveImagesFromPost(userID, postID, publicIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveImagesFromPost", reflect.TypeOf((*MockPostService)(nil).RemoveImagesFromPost), userID, postID, publicIDs)
}

// RemovePollOptions mocks base method.
func (m *MockPostService) RemovePollOptions(userID, postID string, optionIDs []string) (*dto.PollResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePollOptions", userID, postID, optionIDs)
	ret0, _ := ret[0].(*dto.PollResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemovePollOptions indicates an expected call of RemovePollOptions.
func (mr *MockPostServiceMockRecorder) RemovePollOptions(userID, postID, optionIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePollOptions", reflect.TypeOf((*MockPostService)(nil).RemovePollOptions), userID, postID, optionIDs)
}

// RemovePollVote mocks base method.
func (m *MockPostService) RemovePollVote(userID, postID string) (*dto.PollResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePollVote", userID, postID)
	ret0, _ := ret[0].(*dto.PollResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemovePollVote indicates an expected call of RemovePollVote.
func (mr *MockPostServiceMockRecorder) RemovePollVote(userID, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePollVote", reflect.TypeOf((*MockPostService)(nil).RemovePollVote), userID, postID)
}

// UpdatePoll mocks base method.
func (m *MockPostService) UpdatePoll(userID, postID string, req *dto.UpdatePollRequest) (*dto.PollResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePoll", userID, postID, req)
	ret0, _ := ret[0].(*dto.PollResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePoll indicates an expected call of UpdatePoll.
func (mr *MockPostServiceMockRecorder) UpdatePoll(userID, postID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePoll", reflect.TypeOf((*MockPostService)(nil).UpdatePoll), userID, postID, req)
}

// UpdatePollOption mocks base method.
func (m *MockPostService) UpdatePollOption(userID, postID, optionID string, req *dto.UpdatePollOptionRequest) (*dto.PollResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePollOption", userID, postID, optionID, req)
	ret0, _ := ret[0].(*dto.PollResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePollOption indicates an expected call of UpdatePollOption.
func (mr *MockPostServiceMockRecorder) UpdatePollOption(userID, postID, optionID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePollOption", reflect.TypeOf((*MockPostService)(nil).UpdatePollOption), userID, postID, optionID, req)
}

// UpdatePost mocks base method.
func (m *MockPostService) UpdatePost(postID, userID string, req *dto.UpdatePostRequest) (*dto.PostResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePost", postID, userID, req)
	ret0, _ := ret[0].(*dto.PostResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePost indicates an expected call of UpdatePost.
func (mr *MockPostServiceMockRecorder) UpdatePost(postID, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePost", reflect.TypeOf((*MockPostService)(nil).UpdatePost), postID, userID, req)
}

// VoteOnPoll mocks base method.
func (m *MockPostService) VoteOnPoll(userID, postID, optionID string) (*dto.PollResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VoteOnPoll", userID, postID, optionID)
	ret0, _ := ret[0].(*dto.PollResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VoteOnPoll indicates an expected call of VoteOnPoll.
func (mr *MockPostServiceMockRecorder) VoteOnPoll(userID, postID, optionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VoteOnPoll", reflect.TypeOf((*MockPostService)(nil).VoteOnPoll), userID, postID, optionID)
}

// VoteOnPost mocks base method.
func (m *MockPostService) VoteOnPost(userID, postID string, voteValue bool) (*dto.VotesCountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VoteOnPost", userID, postID, voteValue)
	ret0, _ := ret[0].(*dto.VotesCountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VoteOnPost indicates an expected call of VoteOnPost.
func (mr *MockPostServiceMockRecorder) VoteOnPost(userID, postID, voteValue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VoteOnPost", reflect.TypeOf((*MockPostService)(nil).VoteOnPost), userID, postID, voteValue)
}
