// Code generated by MockGen. DO NOT EDIT.
// Source: ../../service/comment_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/giakiet05/lkforum/internal/dto"
	model "github.com/giakiet05/lkforum/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockCommentService is a mock of CommentService interface.
type MockCommentService struct {
	ctrl     *gomock.Controller
	recorder *MockCommentServiceMockRecorder
}

// MockCommentServiceMockRecorder is the mock recorder for MockCommentService.
type MockCommentServiceMockRecorder struct {
	mock *MockCommentService
}

// NewMockCommentService creates a new mock instance.
func NewMockCommentService(ctrl *gomock.Controller) *MockCommentService {
	mock := &MockCommentService{ctrl: ctrl}
	mock.recorder = &MockCommentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentService) EXPECT() *MockCommentServiceMockRecorder {
	return m.recorder
}

// CreateComment mocks base method.
func (m *MockCommentService) CreateComment(request *dto.CreateCommentRequest, userID string) (*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", request, userID)
	ret0, _ := ret[0].(*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockCommentServiceMockRecorder) CreateComment(request, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockCommentService)(nil).CreateComment), request, userID)
}

// DeleteCommentByID mocks base method.
func (m *MockCommentService) DeleteCommentByID(commentID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCommentByID", commentID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCommentByID indicates an expected call of DeleteCommentByID.
func (mr *MockCommentServiceMockRecorder) DeleteCommentByID(commentID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCommentByID", reflect.TypeOf((*MockCommentService)(nil).DeleteCommentByID), commentID, userID)
}

// GetAllChildren mocks base method.
func (m *MockCommentService) GetAllChildren(commentID string) ([]model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllChildren", commentID)
	ret0, _ := ret[0].([]model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllChildren indicates an expected call of GetAllChildren.
func (mr *MockCommentServiceMockRecorder) GetAllChildren(commentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllChildren", reflect.TypeOf((*MockCommentService)(nil).GetAllChildren), commentID)
}

// GetCommentByID mocks base method.
func (m *MockCommentService) GetCommentByID(commentID string) (*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentByID", commentID)
	ret0, _ := ret[0].(*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentByID indicates an expected call of GetCommentByID.
func (mr *MockCommentServiceMockRecorder) GetCommentByID(commentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentByID", reflect.TypeOf((*MockCommentService)(nil).GetCommentByID), commentID)
}

// GetCommentByPostIDPaginated mocks base method.
func (m *MockCommentService) GetCommentByPostIDPaginated(query *dto.GetCommentByPostIDQuery) (*dto.PaginatedCommentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentByPostIDPaginated", query)
	ret0, _ := ret[0].(*dto.PaginatedCommentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentByPostIDPaginated indicates an expected call of GetCommentByPostIDPaginated.
func (mr *MockCommentServiceMockRecorder) GetCommentByPostIDPaginated(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentByPostIDPaginated", reflect.TypeOf((*MockCommentService)(nil).GetCommentByPostIDPaginated), query)
}

// GetCommentsFilterPaginated mocks base method.
func (m *MockCommentService) GetCommentsFilterPaginated(query *dto.GetCommentsFilterQuery) (*dto.PaginatedCommentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentsFilterPaginated", query)
	ret0, _ := ret[0].(*dto.PaginatedCommentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentsFilterPaginated indicates an expected call of GetCommentsFilterPaginated.
func (mr *MockCommentServiceMockRecorder) GetCommentsFilterPaginated(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentsFilterPaginated", reflect.TypeOf((*MockCommentService)(nil).GetCommentsFilterPaginated), query)
}
