// Code generated by MockGen. DO NOT EDIT.
// Source: ../../service/reputation_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockReputationService is a mock of ReputationService interface.
type MockReputationService struct {
	ctrl     *gomock.Controller
	recorder *MockReputationServiceMockRecorder
}

// MockReputationServiceMockRecorder is the mock recorder for MockReputationService.
type MockReputationServiceMockRecorder struct {
	mock *MockReputationService
}

// NewMockReputationService creates a new mock instance.
func NewMockReputationService(ctrl *gomock.Controller) *MockReputationService {
	mock := &MockReputationService{ctrl: ctrl}
	mock.recorder = &MockReputationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReputationService) EXPECT() *MockReputationServiceMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockReputationService) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockReputationServiceMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockReputationService)(nil).Start))
}
