// Code generated by MockGen. DO NOT EDIT.
// Source: ../../service/channel_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/giakiet05/lkforum/internal/dto"
	model "github.com/giakiet05/lkforum/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockChannelService is a mock of ChannelService interface.
type MockChannelService struct {
	ctrl     *gomock.Controller
	recorder *MockChannelServiceMockRecorder
}

// MockChannelServiceMockRecorder is the mock recorder for MockChannelService.
type MockChannelServiceMockRecorder struct {
	mock *MockChannelService
}

// NewMockChannelService creates a new mock instance.
func NewMockChannelService(ctrl *gomock.Controller) *MockChannelService {
	mock := &MockChannelService{ctrl: ctrl}
	mock.recorder = &MockChannelServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelService) EXPECT() *MockChannelServiceMockRecorder {
	return m.recorder
}

// CreateChannel mocks base method.
func (m *MockChannelService) CreateChannel(req *dto.CreateChannelRequest, userID string) (*model.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChannel", req, userID)
	ret0, _ := ret[0].(*model.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChannel indicates an expected call of CreateChannel.
func (mr *MockChannelServiceMockRecorder) CreateChannel(req, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChannel", reflect.TypeOf((*MockChannelService)(nil).CreateChannel), req, userID)
}

// DeleteChannel mocks base method.
func (m *MockChannelService) DeleteChannel(channelID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChannel", channelID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChannel indicates an expected call of DeleteChannel.
func (mr *MockChannelServiceMockRecorder) DeleteChannel(channelID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChannel", reflect.TypeOf((*MockChannelService)(nil).DeleteChannel), channelID, userID)
}

// GetChannelByBothUserID mocks base method.
func (m *MockChannelService) GetChannelByBothUserID(user1ID, user2ID, requesterID string) (*model.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelByBothUserID", user1ID, user2ID, requesterID)
	ret0, _ := ret[0].(*model.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannelByBothUserID indicates an expected call of GetChannelByBothUserID.
func (mr *MockChannelServiceMockRecorder) GetChannelByBothUserID(user1ID, user2ID, requesterID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelByBothUserID", reflect.TypeOf((*MockChannelService)(nil).GetChannelByBothUserID), user1ID, user2ID, requesterID)
}

// GetChannelByID mocks base method.
func (m *MockChannelService) GetChannelByID(channelID string) (*model.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelByID", channelID)
	ret0, _ := ret[0].(*model.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannelByID indicates an expected call of GetChannelByID.
func (mr *MockChannelServiceMockRecorder) GetChannelByID(channelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelByID", reflect.TypeOf((*MockChannelService)(nil).GetChannelByID), channelID)
}

// GetChannelsByUserID mocks base method.
func (m *MockChannelService) GetChannelsByUserID(userID, requesterID string, page, pageSize int) (*dto.PaginatedChannelsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelsByUserID", userID, requesterID, page, pageSize)
	ret0, _ := ret[0].(*dto.PaginatedChannelsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannelsByUserID indicates an expected call of GetChannelsByUserID.
func (mr *MockChannelServiceMockRecorder) GetChannelsByUserID(userID, requesterID, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelsByUserID", reflect.TypeOf((*MockChannelService)(nil).GetChannelsByUserID), userID, requesterID, page, pageSize)
}

// Start mocks base method.
func (m *MockChannelService) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockChannelServiceMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockChannelService)(nil).Start))
}

// UpdateChannel mocks base method.
func (m *MockChannelService) UpdateChannel(req *dto.UpdateChannelRequest, requesterID string) (*model.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChannel", req, requesterID)
	ret0, _ := ret[0].(*model.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateChannel indicates an expected call of UpdateChannel.
func (mr *MockChannelServiceMockRecorder) UpdateChannel(req, requesterID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChannel", reflect.TypeOf((*MockChannelService)(nil).UpdateChannel), req, requesterID)
}
