// Code generated by MockGen. DO NOT EDIT.
// Source: ../../repo/post_vote_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/giakiet05/lkforum/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockPostVoteRepo is a mock of PostVoteRepo interface.
type MockPostVoteRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPostVoteRepoMockRecorder
}

// MockPostVoteRepoMockRecorder is the mock recorder for MockPostVoteRepo.
type MockPostVoteRepoMockRecorder struct {
	mock *MockPostVoteRepo
}

// NewMockPostVoteRepo creates a new mock instance.
func NewMockPostVoteRepo(ctrl *gomock.Controller) *MockPostVoteRepo {
	mock := &MockPostVoteRepo{ctrl: ctrl}
	mock.recorder = &MockPostVoteRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostVoteRepo) EXPECT() *MockPostVoteRepoMockRecorder {
	return m.recorder
}

// FindUserVotes mocks base method.
func (m *MockPostVoteRepo) FindUserVotes(ctx context.Context, userID string, postIDs []string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserVotes", ctx, userID, postIDs)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserVotes indicates an expected call of FindUserVotes.
func (mr *MockPostVoteRepoMockRecorder) FindUserVotes(ctx, userID, postIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserVotes", reflect.TypeOf((*MockPostVoteRepo)(nil).FindUserVotes), ctx, userID, postIDs)
}

// GetUserVote mocks base method.
func (m *MockPostVoteRepo) GetUserVote(ctx context.Context, userID, postID string) (*model.Vote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserVote", ctx, userID, postID)
	ret0, _ := ret[0].(*model.Vote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserVote indicates an expected call of GetUserVote.
func (mr *MockPostVoteRepoMockRecorder) GetUserVote(ctx, userID, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserVote", reflect.TypeOf((*MockPostVoteRepo)(nil).GetUserVote), ctx, userID, postID)
}

// RemoveVote mocks base method.
func (m *MockPostVoteRepo) RemoveVote(ctx context.Context, userID, postID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveVote", ctx, userID, postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveVote indicates an expected call of RemoveVote.
func (mr *MockPostVoteRepoMockRecorder) RemoveVote(ctx, userID, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveVote", reflect.TypeOf((*MockPostVoteRepo)(nil).RemoveVote), ctx, userID, postID)
}

// Vote mocks base method.
func (m *MockPostVoteRepo) Vote(ctx context.Context, userID, postID string, voteValue bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Vote", ctx, userID, postID, voteValue)
	ret0, _ := ret[0].(error)
	return ret0
}

// Vote indicates an expected call of Vote.
func (mr *MockPostVoteRepoMockRecorder) Vote(ctx, userID, postID, voteValue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Vote", reflect.TypeOf((*MockPostVoteRepo)(nil).Vote), ctx, userID, postID, voteValue)
}
