// Code generated by MockGen. DO NOT EDIT.
// Source: ../../repo/community_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/giakiet05/lkforum/internal/model"
	gomock "github.com/golang/mock/gomock"
	bson "go.mongodb.org/mongo-driver/bson"
)

// MockCommunityRepo is a mock of CommunityRepo interface.
type MockCommunityRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCommunityRepoMockRecorder
}

// MockCommunityRepoMockRecorder is the mock recorder for MockCommunityRepo.
type MockCommunityRepoMockRecorder struct {
	mock *MockCommunityRepo
}

// NewMockCommunityRepo creates a new mock instance.
func NewMockCommunityRepo(ctrl *gomock.Controller) *MockCommunityRepo {
	mock := &MockCommunityRepo{ctrl: ctrl}
	mock.recorder = &MockCommunityRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommunityRepo) EXPECT() *MockCommunityRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCommunityRepo) Create(ctx context.Context, community *model.Community) (*model.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, community)
	ret0, _ := ret[0].(*model.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCommunityRepoMockRecorder) Create(ctx, community interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCommunityRepo)(nil).Create), ctx, community)
}

// Delete mocks base method.
func (m *MockCommunityRepo) Delete(ctx context.Context, communityID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, communityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCommunityRepoMockRecorder) Delete(ctx, communityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCommunityRepo)(nil).Delete), ctx, communityID)
}

// GetAllPaginated mocks base method.
func (m *MockCommunityRepo) GetAllPaginated(ctx context.Context, page, pageSize int) ([]model.Community, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPaginated", ctx, page, pageSize)
	ret0, _ := ret[0].([]model.Community)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllPaginated indicates an expected call of GetAllPaginated.
func (mr *MockCommunityRepoMockRecorder) GetAllPaginated(ctx, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPaginated", reflect.TypeOf((*MockCommunityRepo)(nil).GetAllPaginated), ctx, page, pageSize)
}

// GetByID mocks base method.
func (m *MockCommunityRepo) GetByID(ctx context.Context, id string) (*model.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCommunityRepoMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCommunityRepo)(nil).GetByID), ctx, id)
}

// GetByIDs mocks base method.
func (m *MockCommunityRepo) GetByIDs(ctx context.Context, ids []string) ([]*model.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].([]*model.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockCommunityRepoMockRecorder) GetByIDs(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockCommunityRepo)(nil).GetByIDs), ctx, ids)
}

// GetByModeratorIDPaginated mocks base method.
func (m *MockCommunityRepo) GetByModeratorIDPaginated(ctx context.Context, moderatorID string, page, pageSize int) ([]model.Community, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByModeratorIDPaginated", ctx, moderatorID, page, pageSize)
	ret0, _ := ret[0].([]model.Community)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByModeratorIDPaginated indicates an expected call of GetByModeratorIDPaginated.
func (mr *MockCommunityRepoMockRecorder) GetByModeratorIDPaginated(ctx, moderatorID, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByModeratorIDPaginated", reflect.TypeOf((*MockCommunityRepo)(nil).GetByModeratorIDPaginated), ctx, moderatorID, page, pageSize)
}

// GetFilter mocks base method.
func (m *MockCommunityRepo) GetFilter(ctx context.Context, name, description string, is18Plus bool, createFrom time.Time, page, pageSize int) ([]model.Community, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilter", ctx, name, description, is18Plus, createFrom, page, pageSize)
	ret0, _ := ret[0].([]model.Community)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFilter indicates an expected call of GetFilter.
func (mr *MockCommunityRepoMockRecorder) GetFilter(ctx, name, description, is18Plus, createFrom, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilter", reflect.TypeOf((*MockCommunityRepo)(nil).GetFilter), ctx, name, description, is18Plus, createFrom, page, pageSize)
}

// IsUserExist mocks base method.
func (m *MockCommunityRepo) IsUserExist(ctx context.Context, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserExist", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserExist indicates an expected call of IsUserExist.
func (mr *MockCommunityRepoMockRecorder) IsUserExist(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserExist", reflect.TypeOf((*MockCommunityRepo)(nil).IsUserExist), ctx, userID)
}

// Replace mocks base method.
func (m *MockCommunityRepo) Replace(ctx context.Context, community *model.Community) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", ctx, community)
	ret0, _ := ret[0].(error)
	return ret0
}

// Replace indicates an expected call of Replace.
func (mr *MockCommunityRepoMockRecorder) Replace(ctx, community interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockCommunityRepo)(nil).Replace), ctx, community)
}

// Update mocks base method.
func (m *MockCommunityRepo) Update(ctx context.Context, communityID string, updates bson.M) (*model.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, communityID, updates)
	ret0, _ := ret[0].(*model.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCommunityRepoMockRecorder) Update(ctx, communityID, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCommunityRepo)(nil).Update), ctx, communityID, updates)
}

// UpdateUserAvatar mocks base method.
func (m *MockCommunityRepo) UpdateUserAvatar(ctx context.Context, userID, newAvatar string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserAvatar", ctx, userID, newAvatar)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserAvatar indicates an expected call of UpdateUserAvatar.
func (mr *MockCommunityRepoMockRecorder) UpdateUserAvatar(ctx, userID, newAvatar interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserAvatar", reflect.TypeOf((*MockCommunityRepo)(nil).UpdateUserAvatar), ctx, userID, newAvatar)
}
