name: API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-api:
    runs-on: ubuntu-latest   # or windows-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install Newman
      - name: Install Newman
        run: npm install -g newman

      # Run Postman collection
      - name: Run Postman tests with Newman
        run: |
          newman run LKForum.postman_collection.json \
            -e LKForum.postman_environment.json \
            --reporters cli,junit \
            --reporter-junit-export newman-results.xml

      # Upload results as artifact
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: newman-results.xml